====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Wed Apr 6 2022
; Processor: 80C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:JNB P1.1,ANGLE_90
	 JNB P1.2,ANGLE_45
	 SJMP  Start
	 ANGLE_90: MOV R1,#80
	 SJMP ROTATE
	 ANGLE_45: mov R1,#113
	 SJMP ROTATE
      SJMP ROTATE
      ROTATE: MOV P2,R1
      CALL T_ON
      CALL T_OFF
      SJMP START
      T_ON:SETb p2.6
      WAIT2:MOV R2,#4
      WAIT1:DJNZ R2,WAIT1
      DJNZ R1,WAIT2
      RET
      T_OFF:CLR P2.6
      MOV R3,#250
      WAIT4:DJNZ R4,WAIT3
      WAIT3:DJNZ R3,WAIT4
      DJNZ R3,WAIT4
      RET
Loop:	
      jmp Loop

;====================================================================
      END
